version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    environment:
      - VITE_API_URL=http://localhost:3000
    restart: unless-stopped
    # Si tienes un backend, puedes descomentar esto para conectarlos
    # depends_on:
    #   - backend 